import {
  ShoppingCartIcon,
  UsersIcon,
  GearIcon,
  BookIcon,
  Volume2Icon,
  ShieldCheck,
  FileDescriptionIcon,
  PenIcon,
  PaintIcon,
} from "@gaqno-development/frontcore/components/icons";
import type { ComponentType } from "react";
import {
  Package,
  DollarSign,
  LayoutDashboard,
  Dices,
  Video,
  Image,
  Mic,
  Music,
} from "lucide-react";

export interface MenuItem {
  id: string;
  label: string;
  href: string;
  icon: ComponentType<{ className?: string; size?: number }>;
  requiredPermissions: string[];
  children?: MenuItem[];
}

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    requiredPermissions: [],
  },
  {
    id: "pdv",
    label: "PDV",
    href: "/pdv",
    icon: ShoppingCartIcon,
    requiredPermissions: ["pdv.access"],
  },
  {
    id: "crm",
    label: "CRM",
    href: "/crm/dashboard",
    icon: UsersIcon,
    requiredPermissions: ["crm.access"],
  },
  {
    id: "erp",
    label: "ERP",
    href: "/erp/dashboard",
    icon: Package,
    requiredPermissions: ["erp.access"],
  },
  {
    id: "finance",
    label: "Financeiro",
    href: "/finance/dashboard",
    icon: DollarSign,
    requiredPermissions: ["finance.access"],
  },
  {
    id: "ai",
    label: "Inteligência Artificial",
    href: "/ai",
    icon: BookIcon,
    requiredPermissions: ["ai.access"],
    children: [
      {
        id: "ai-audio",
        label: "Áudio",
        href: "/ai/audio",
        icon: Volume2Icon,
        requiredPermissions: ["ai.access"],
        children: [
          {
            id: "ai-audio-tts",
            label: "Texto para Audio",
            href: "/ai/audio/tts",
            icon: Volume2Icon,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-audio-stt",
            label: "Audio para Texto",
            href: "/ai/audio/stt",
            icon: Mic,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-audio-music",
            label: "Música",
            href: "/ai/audio/music",
            icon: Music,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-audio-isolation",
            label: "Isolar Audio",
            href: "/ai/audio/isolation",
            icon: ShieldCheck,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-audio-podcast",
            label: "Podcast",
            href: "/ai/audio/podcast",
            icon: BookIcon,
            requiredPermissions: ["ai.access"],
          },
        ],
      },
      {
        id: "ai-images",
        label: "Imagem",
        href: "/ai/images",
        icon: Image,
        requiredPermissions: ["ai.access"],
        children: [
          {
            id: "ai-images-text",
            label: "Texto para Imagem",
            href: "/ai/images/text",
            icon: FileDescriptionIcon,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-images-edit",
            label: "Editar Imagem",
            href: "/ai/images/edit",
            icon: PenIcon,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-images-inpainting",
            label: "Inpainting",
            href: "/ai/images/inpainting",
            icon: PaintIcon,
            requiredPermissions: ["ai.access"],
          },
        ],
      },
      {
        id: "ai-video",
        label: "Vídeo",
        href: "/ai/video",
        icon: Video,
        requiredPermissions: ["ai.access"],
        children: [
          {
            id: "ai-video-modify",
            label: "Modificar Vídeo",
            href: "/ai/video/modify",
            icon: Video,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-video-reference",
            label: "Usar Referência",
            href: "/ai/video/reference",
            icon: Video,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-video-text",
            label: "Texto para Vídeo",
            href: "/ai/video/text",
            icon: FileDescriptionIcon,
            requiredPermissions: ["ai.access"],
          },
        ],
      },
      {
        id: "ai-books",
        label: "Livros",
        href: "/ai/books",
        icon: BookIcon,
        requiredPermissions: ["ai.books.read"],
      },
      {
        id: "ai-retail",
        label: "Retail",
        href: "/ai/retail/profile",
        icon: Package,
        requiredPermissions: ["ai.access"],
        children: [
          {
            id: "ai-retail-profile",
            label: "Perfil do Produto",
            href: "/ai/retail/profile",
            icon: Package,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-retail-content",
            label: "Gerar Conteudo",
            href: "/ai/retail/content",
            icon: FileDescriptionIcon,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-retail-video",
            label: "Video de Produto",
            href: "/ai/retail/video",
            icon: Video,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-retail-distribution",
            label: "Distribuicao",
            href: "/ai/retail/distribution",
            icon: Package,
            requiredPermissions: ["ai.access"],
          },
          {
            id: "ai-retail-attribution",
            label: "Atribuicao GMV",
            href: "/ai/retail/attribution",
            icon: DollarSign,
            requiredPermissions: ["ai.access"],
          },
        ],
      },
    ],
  },
  {
    id: "rpg",
    label: "RPG",
    href: "/rpg",
    icon: Dices,
    requiredPermissions: ["rpg.access"],
  },
  {
    id: "omnichannel",
    label: "Omnichannel",
    href: "/omnichannel",
    icon: Package,
    requiredPermissions: ["omnichannel.access"],
  },
  {
    id: "admin",
    label: "Administração",
    href: "/admin/dashboard",
    icon: GearIcon,
    requiredPermissions: ["admin.access"],
  },
];

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  "/dashboard": [],
  "/pdv": ["pdv.access"],
  "/pdv/sales": ["pdv.sales.read"],
  "/pdv/products": ["pdv.products.manage"],
  "/pdv/inventory": ["pdv.inventory.read"],
  "/pdv/settings": ["pdv.settings.write"],
  "/crm/dashboard": ["crm.access"],
  "/crm/dashboard/overview": ["crm.access"],
  "/crm/dashboard/kpis": ["crm.access"],
  "/crm/dashboard/activity-feed": ["crm.access"],
  "/crm/dashboard/alerts": ["crm.access"],
  "/crm/sales": ["crm.access"],
  "/crm/sales/leads": ["crm.access"],
  "/crm/sales/opportunities": ["crm.access"],
  "/crm/sales/deals": ["crm.access"],
  "/crm/sales/quotes": ["crm.access"],
  "/crm/sales/contracts": ["crm.access"],
  "/crm/sales/orders": ["crm.access"],
  "/crm/customers": ["crm.access"],
  "/crm/customers/accounts": ["crm.access"],
  "/crm/customers/contacts": ["crm.access"],
  "/crm/customers/profiles": ["crm.access"],
  "/crm/customers/interaction-history": ["crm.access"],
  "/crm/customers/support-tickets": ["crm.access"],
  "/crm/inventory": ["crm.access"],
  "/crm/inventory/products": ["crm.access"],
  "/crm/inventory/categories": ["crm.access"],
  "/crm/inventory/stock-levels": ["crm.access"],
  "/crm/inventory/warehouses": ["crm.access"],
  "/crm/inventory/suppliers": ["crm.access"],
  "/crm/operations": ["crm.access"],
  "/crm/operations/order-fulfillment": ["crm.access"],
  "/crm/operations/shipping": ["crm.access"],
  "/crm/operations/returns": ["crm.access"],
  "/crm/operations/invoicing": ["crm.access"],
  "/crm/finance": ["crm.access"],
  "/crm/finance/invoices": ["crm.access"],
  "/crm/finance/payments": ["crm.access"],
  "/crm/finance/pricing-rules": ["crm.access"],
  "/crm/finance/taxes": ["crm.access"],
  "/crm/reports": ["crm.access"],
  "/crm/reports/analytics": ["crm.access"],
  "/crm/reports/sales-reports": ["crm.access"],
  "/crm/reports/customer-insights": ["crm.access"],
  "/crm/reports/inventory-reports": ["crm.access"],
  "/crm/reports/financial-reports": ["crm.access"],
  "/crm/reports/custom-reports": ["crm.access"],
  "/crm/automation": ["crm.access"],
  "/crm/automation/workflows": ["crm.access"],
  "/crm/automation/triggers": ["crm.access"],
  "/crm/automation/webhooks": ["crm.access"],
  "/crm/automation/integrations": ["crm.access"],
  "/crm/administration": ["crm.access"],
  "/crm/administration/users": ["crm.access"],
  "/crm/administration/permissions": ["crm.access"],
  "/crm/administration/teams": ["crm.access"],
  "/crm/administration/audit-logs": ["crm.access"],
  "/crm/administration/system-settings": ["crm.access"],
  "/crm/settings": ["crm.access"],
  "/crm/settings/organization": ["crm.access"],
  "/crm/settings/custom-fields": ["crm.access"],
  "/crm/settings/pipelines": ["crm.access"],
  "/crm/settings/notifications": ["crm.access"],
  "/crm/settings/api-keys": ["crm.access"],
  "/crm": ["crm.access"],
  "/erp/dashboard": ["erp.access"],
  "/finance/dashboard": ["finance.access"],
  "/ai/dashboard": ["ai.access"],
  "/admin/dashboard": ["admin.access"],
  "/erp": ["erp.access"],
  "/erp/inventory": ["erp.inventory.read"],
  "/erp/orders": ["erp.orders.read"],
  "/erp/settings": ["erp.settings.write"],
  "/finance": ["finance.access"],
  "/finance/transactions": ["finance.transactions.read"],
  "/finance/accounts": ["finance.accounts.manage"],
  "/finance/reports": ["finance.reports.view"],
  "/finance/investments": ["finance.investments.read"],
  "/finance/settings": ["finance.settings.write"],
  "/ai": ["ai.access"],
  "/ai/video": ["ai.access"],
  "/ai/video/modify": ["ai.access"],
  "/ai/video/reference": ["ai.access"],
  "/ai/video/text": ["ai.access"],
  "/ai/images": ["ai.access"],
  "/ai/images/text": ["ai.access"],
  "/ai/images/edit": ["ai.access"],
  "/ai/images/inpainting": ["ai.access"],
  "/ai/audio": ["ai.access"],
  "/ai/audio/tts": ["ai.access"],
  "/ai/audio/stt": ["ai.access"],
  "/ai/audio/music": ["ai.access"],
  "/ai/audio/voice": ["ai.access"],
  "/ai/audio/sfx": ["ai.access"],
  "/ai/audio/isolation": ["ai.access"],
  "/ai/audio/podcast": ["ai.access"],
  "/ai/books": ["ai.books.read"],
  "/ai/insights": ["ai.insights.view"],
  "/ai/avatar": ["ai.avatar.create"],
  "/ai/portrait": ["ai.portrait.create"],
  "/ai/retail": ["ai.access"],
  "/ai/retail/profile": ["ai.access"],
  "/ai/retail/content": ["ai.access"],
  "/ai/retail/video": ["ai.access"],
  "/ai/retail/distribution": ["ai.access"],
  "/ai/retail/attribution": ["ai.access"],
  "/rpg": ["rpg.access"],
  "/rpg/sessions": ["rpg.access"],
  "/rpg/sessions/:id": ["rpg.access"],
  "/rpg/campaigns": ["rpg.access"],
  "/rpg/campaigns/:id": ["rpg.access"],
  "/rpg/campaigns/new": ["rpg.access"],
  "/rpg/wiki": ["rpg.access"],
  "/rpg/rules": ["rpg.access"],
  "/rpg/characters": ["rpg.access"],
  "/omnichannel": ["omnichannel.access"],
  "/omnichannel/overview": ["omnichannel.access"],
  "/omnichannel/dashboard": ["omnichannel.access"],
  "/omnichannel/inbox": ["omnichannel.access"],
  "/omnichannel/inbox/conversations": ["omnichannel.access"],
  "/omnichannel/inbox/queues": ["omnichannel.access"],
  "/omnichannel/inbox/saved-views": ["omnichannel.access"],
  "/omnichannel/customers": ["omnichannel.access"],
  "/omnichannel/agents": ["omnichannel.access"],
  "/omnichannel/automation": ["omnichannel.access"],
  "/omnichannel/automation/routing": ["omnichannel.access"],
  "/omnichannel/automation/sla": ["omnichannel.access"],
  "/omnichannel/automation/business-hours": ["omnichannel.access"],
  "/omnichannel/reports": ["omnichannel.access"],
  "/omnichannel/reports/conversations": ["omnichannel.access"],
  "/omnichannel/reports/agents": ["omnichannel.access"],
  "/omnichannel/reports/channels": ["omnichannel.access"],
  "/omnichannel/settings": ["omnichannel.access"],
  "/omnichannel/settings/organization": ["omnichannel.access"],
  "/omnichannel/settings/channels": ["omnichannel.access"],
  "/omnichannel/settings/access": ["omnichannel.access"],
  "/omnichannel/settings/integrations": ["omnichannel.access"],
  "/omnichannel/settings/system": ["omnichannel.access"],
  "/admin": ["admin.access"],
  "/admin/users": ["admin.users.manage", "admin.users.read"],
  "/admin/users/new": ["admin.users.manage"],
  "/admin/users/:id/edit": ["admin.users.manage"],
  "/admin/tenants": ["admin.tenants.manage"],
  "/admin/tenants/new": ["admin.tenants.manage"],
  "/admin/tenants/:id/edit": ["admin.tenants.manage"],
  "/admin/branches": ["admin.branches.manage"],
  "/admin/branches/new": ["admin.branches.manage"],
  "/admin/branches/:id/edit": ["admin.branches.manage"],
  "/admin/roles": ["admin.roles.read", "admin.roles.manage"],
  "/admin/menu": ["admin.menu.manage"],
  "/admin/settings": ["admin.settings.write"],
  "/admin/costing": ["admin.tenants.costs.read"],
  "/admin/usage": ["admin.usage.read"],
  "/dashboard/settings": ["admin.settings.read"],
  "/dashboard/profile": [],
  "/sso/users": ["admin.users.read"],
};
