import { 
  ShoppingCart, 
  Users, 
  Package, 
  DollarSign, 
  Settings, 
  BookOpen,
  LayoutDashboard,
  Dices,
  Video,
  Image,
  Volume2,
  Mic,
  Music,
  Shield,
  FileText,
  Edit,
  Paintbrush,
} from 'lucide-react';

export interface MenuItem {
  id: string;
  label: string;
  href: string;
  icon: any;
  requiredPermissions: string[];
  children?: MenuItem[];
}

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    requiredPermissions: ['dashboard.access'],
  },
  {
    id: 'pdv',
    label: 'PDV',
    href: '/pdv',
    icon: ShoppingCart,
    requiredPermissions: ['pdv.access'],
  },
  {
    id: 'crm',
    label: 'CRM',
    href: '/crm/dashboard',
    icon: Users,
    requiredPermissions: ['crm.access'],
  },
  {
    id: 'erp',
    label: 'ERP',
    href: '/erp/dashboard',
    icon: Package,
    requiredPermissions: ['erp.access'],
  },
  {
    id: 'finance',
    label: 'Financeiro',
    href: '/finance/dashboard',
    icon: DollarSign,
    requiredPermissions: ['finance.access'],
  },
  {
    id: 'ai',
    label: 'Inteligência Artificial',
    href: '/ai',
    icon: BookOpen,
    requiredPermissions: ['ai.access'],
    children: [
      {
        id: 'ai-audio',
        label: 'Áudio',
        href: '/ai/audio',
        icon: Volume2,
        requiredPermissions: ['ai.access'],
        children: [
          { id: 'ai-audio-tts', label: 'Texto para Audio', href: '/ai/audio/tts', icon: Volume2, requiredPermissions: ['ai.access'] },
          { id: 'ai-audio-stt', label: 'Audio para Texto', href: '/ai/audio/stt', icon: Mic, requiredPermissions: ['ai.access'] },
          { id: 'ai-audio-music', label: 'Música', href: '/ai/audio/music', icon: Music, requiredPermissions: ['ai.access'] },
          { id: 'ai-audio-isolation', label: 'Isolar Audio', href: '/ai/audio/isolation', icon: Shield, requiredPermissions: ['ai.access'] },
          { id: 'ai-audio-podcast', label: 'Podcast', href: '/ai/audio/podcast', icon: BookOpen, requiredPermissions: ['ai.access'] },
        ],
      },
      {
        id: 'ai-images',
        label: 'Imagem',
        href: '/ai/images',
        icon: Image,
        requiredPermissions: ['ai.access'],
        children: [
          { id: 'ai-images-text', label: 'Texto para Imagem', href: '/ai/images/text', icon: FileText, requiredPermissions: ['ai.access'] },
          { id: 'ai-images-edit', label: 'Editar Imagem', href: '/ai/images/edit', icon: Edit, requiredPermissions: ['ai.access'] },
          { id: 'ai-images-inpainting', label: 'Inpainting', href: '/ai/images/inpainting', icon: Paintbrush, requiredPermissions: ['ai.access'] },
        ],
      },
      {
        id: 'ai-video',
        label: 'Vídeo',
        href: '/ai/video',
        icon: Video,
        requiredPermissions: ['ai.access'],
        children: [
          { id: 'ai-video-modify', label: 'Modificar Vídeo', href: '/ai/video/modify', icon: Video, requiredPermissions: ['ai.access'] },
          { id: 'ai-video-reference', label: 'Usar Referência', href: '/ai/video/reference', icon: Video, requiredPermissions: ['ai.access'] },
          { id: 'ai-video-text', label: 'Texto para Vídeo', href: '/ai/video/text', icon: FileText, requiredPermissions: ['ai.access'] },
        ],
      },
      {
        id: 'ai-books',
        label: 'Livros',
        href: '/ai/books',
        icon: BookOpen,
        requiredPermissions: ['ai.books.read'],
      },
    ],
  },
  {
    id: 'rpg',
    label: 'RPG',
    href: '/rpg',
    icon: Dices,
    requiredPermissions: ['rpg.access'],
  },
  {
    id: 'admin',
    label: 'Administração',
    href: '/admin/dashboard',
    icon: Settings,
    requiredPermissions: ['admin.access'],
  },
];

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  '/dashboard': ['dashboard.access'],
  '/pdv': ['pdv.access'],
  '/pdv/sales': ['pdv.sales.read'],
  '/pdv/products': ['pdv.products.manage'],
  '/pdv/inventory': ['pdv.inventory.read'],
  '/pdv/settings': ['pdv.settings.write'],
  '/crm/dashboard': ['crm.access'],
  '/erp/dashboard': ['erp.access'],
  '/finance/dashboard': ['finance.access'],
  '/ai/dashboard': ['ai.access'],
  '/admin/dashboard': ['admin.access'],
  '/crm': ['crm.access'],
  '/crm/contacts': ['crm.contacts.read'],
  '/crm/deals': ['crm.deals.read'],
  '/crm/pipeline': ['crm.pipeline.manage'],
  '/crm/settings': ['crm.settings.write'],
  '/erp': ['erp.access'],
  '/erp/inventory': ['erp.inventory.read'],
  '/erp/orders': ['erp.orders.read'],
  '/erp/settings': ['erp.settings.write'],
  '/finance': ['finance.access'],
  '/finance/transactions': ['finance.transactions.read'],
  '/finance/accounts': ['finance.accounts.manage'],
  '/finance/reports': ['finance.reports.view'],
  '/finance/investments': ['finance.investments.read'],
  '/finance/settings': ['finance.settings.write'],
  '/ai': ['ai.access'],
  '/ai/video': ['ai.access'],
  '/ai/video/modify': ['ai.access'],
  '/ai/video/reference': ['ai.access'],
  '/ai/video/text': ['ai.access'],
  '/ai/images': ['ai.access'],
  '/ai/images/text': ['ai.access'],
  '/ai/images/edit': ['ai.access'],
  '/ai/images/inpainting': ['ai.access'],
  '/ai/audio': ['ai.access'],
  '/ai/audio/tts': ['ai.access'],
  '/ai/audio/stt': ['ai.access'],
  '/ai/audio/music': ['ai.access'],
  '/ai/audio/voice': ['ai.access'],
  '/ai/audio/sfx': ['ai.access'],
  '/ai/audio/isolation': ['ai.access'],
  '/ai/audio/podcast': ['ai.access'],
  '/ai/books': ['ai.books.read'],
  '/ai/insights': ['ai.insights.view'],
  '/ai/avatar': ['ai.avatar.create'],
  '/ai/portrait': ['ai.portrait.create'],
  '/rpg': ['rpg.access'],
  '/rpg/sessions': ['rpg.access'],
  '/rpg/sessions/:id': ['rpg.access'],
  '/rpg/campaigns': ['rpg.access'],
  '/rpg/campaigns/:id': ['rpg.access'],
  '/rpg/campaigns/new': ['rpg.access'],
  '/rpg/wiki': ['rpg.access'],
  '/rpg/rules': ['rpg.access'],
  '/rpg/characters': ['rpg.access'],
  '/admin': ['admin.access'],
  '/admin/users': ['admin.users.manage'],
  '/admin/tenants': ['admin.tenants.manage'],
  '/admin/branches': ['admin.branches.manage'],
  '/admin/settings': ['admin.settings.write'],
  '/dashboard/settings': ['admin.settings.read'],
  '/sso/users': ['admin.users.read'],
}

