import {
  AnimatedBellIcon,
  AnimatedDicesIcon,
  AnimatedGearIcon,
  AnimatedLightbulbIcon,
  AnimatedShoppingCartIcon,
  AnimatedSparklesIcon,
  AnimatedTrendingUpIcon,
  BoxesIcon,
  DollarSignIcon,
  FileDescriptionIcon,
  LayoutPanelTopIcon,
  ShieldCheck,
  UsersIcon,
} from "@gaqno-development/frontcore/components/icons";
import { Activity, Heart } from "lucide-react";
import type { ComponentType } from "react";

export interface MenuItem {
  id: string;
  label: string;
  href: string;
  icon: ComponentType<{ className?: string; size?: number }>;
  requiredPermissions: string[];
  children?: MenuItem[];
}

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "overview",
    label: "Visão Geral",
    href: "/dashboard",
    icon: LayoutPanelTopIcon,
    requiredPermissions: [],
    children: [
      { id: "overview-dashboard", label: "Dashboard", href: "/dashboard", icon: LayoutPanelTopIcon, requiredPermissions: [] },
      { id: "overview-tasks", label: "Tarefas", href: "/dashboard/tasks", icon: FileDescriptionIcon, requiredPermissions: [] },
      { id: "overview-calendar", label: "Agenda", href: "/dashboard/calendar", icon: LayoutPanelTopIcon, requiredPermissions: [] },
      { id: "overview-notifications", label: "Notificações", href: "/dashboard/notifications", icon: AnimatedBellIcon, requiredPermissions: [] },
    ],
  },
  {
    id: "commercial",
    label: "Comercial",
    href: "/crm/dashboard/overview",
    icon: AnimatedTrendingUpIcon,
    requiredPermissions: ["crm.access"],
    children: [
      { id: "commercial-customers", label: "Clientes", href: "/crm/customers/accounts", icon: UsersIcon, requiredPermissions: ["crm.access"] },
      { id: "commercial-pipeline", label: "Pipeline", href: "/crm/sales/leads", icon: AnimatedTrendingUpIcon, requiredPermissions: ["crm.access"] },
      { id: "commercial-proposals", label: "Propostas", href: "/crm/sales/quotes", icon: FileDescriptionIcon, requiredPermissions: ["crm.access"] },
      { id: "commercial-sales", label: "Vendas", href: "/crm/sales/leads", icon: AnimatedTrendingUpIcon, requiredPermissions: ["crm.access"] },
      { id: "commercial-performance", label: "Desempenho", href: "/crm/reports/analytics", icon: FileDescriptionIcon, requiredPermissions: ["crm.access"] },
    ],
  },
  {
    id: "support",
    label: "Atendimento",
    href: "/omnichannel/overview",
    icon: AnimatedBellIcon,
    requiredPermissions: ["omnichannel.access"],
    children: [
      { id: "support-inbox", label: "Inbox", href: "/omnichannel/inbox/conversations", icon: FileDescriptionIcon, requiredPermissions: ["omnichannel.access"] },
      { id: "support-tickets", label: "Tickets", href: "/omnichannel/inbox/conversations", icon: FileDescriptionIcon, requiredPermissions: ["omnichannel.access"] },
      { id: "support-contacts", label: "Contatos", href: "/omnichannel/customers", icon: UsersIcon, requiredPermissions: ["omnichannel.access"] },
      { id: "support-automation", label: "Automação", href: "/omnichannel/automation/routing", icon: ShieldCheck, requiredPermissions: ["omnichannel.access"] },
      { id: "support-metrics", label: "Métricas", href: "/omnichannel/reports/conversations", icon: FileDescriptionIcon, requiredPermissions: ["omnichannel.access"] },
    ],
  },
  {
    id: "operations",
    label: "Operações",
    href: "/erp/dashboard",
    icon: BoxesIcon,
    requiredPermissions: ["erp.access"],
    children: [
      { id: "operations-inventory", label: "Estoque", href: "/erp/inventory", icon: BoxesIcon, requiredPermissions: ["erp.inventory.read"] },
      { id: "operations-orders", label: "Pedidos", href: "/erp/orders", icon: BoxesIcon, requiredPermissions: ["erp.orders.read"] },
      { id: "operations-purchasing", label: "Compras", href: "/erp/purchasing", icon: BoxesIcon, requiredPermissions: ["erp.access"] },
      { id: "operations-catalog", label: "Catálogo", href: "/erp/catalog", icon: BoxesIcon, requiredPermissions: ["erp.access"] },
      { id: "operations-logistics", label: "Logística", href: "/erp/logistics", icon: BoxesIcon, requiredPermissions: ["erp.access"] },
    ],
  },
  {
    id: "finance",
    label: "Financeiro",
    href: "/finance/dashboard",
    icon: DollarSignIcon,
    requiredPermissions: ["finance.access"],
  },
  {
    id: "intelligence",
    label: "Inteligência",
    href: "/intelligence",
    icon: AnimatedLightbulbIcon,
    requiredPermissions: [],
  },
  {
    id: "consumer",
    label: "Consumer",
    href: "/consumer",
    icon: Activity,
    requiredPermissions: [],
    children: [
      { id: "consumer-dashboard", label: "Dashboard", href: "/consumer/dashboard", icon: LayoutPanelTopIcon, requiredPermissions: [] },
    ],
  },
  {
    id: "ai-studio",
    label: "AI Studio",
    href: "/ai",
    icon: AnimatedSparklesIcon,
    requiredPermissions: ["ai.access"],
    children: [
      { id: "ai-generation", label: "Geração", href: "/ai/audio", icon: AnimatedSparklesIcon, requiredPermissions: ["ai.access"] },
      { id: "ai-marketing", label: "Marketing", href: "/ai/studio", icon: AnimatedTrendingUpIcon, requiredPermissions: ["ai.access"] },
      { id: "ai-retail", label: "Varejo", href: "/ai/retail/profile", icon: BoxesIcon, requiredPermissions: ["ai.access"] },
      { id: "ai-library", label: "Biblioteca", href: "/ai/books", icon: FileDescriptionIcon, requiredPermissions: ["ai.access"] },
    ],
  },
  {
    id: "pdv",
    label: "PDV",
    href: "/pdv",
    icon: AnimatedShoppingCartIcon,
    requiredPermissions: ["pdv.access"],
    children: [
      { id: "pdv-register", label: "Caixa", href: "/pdv", icon: LayoutPanelTopIcon, requiredPermissions: ["pdv.access"] },
      { id: "pdv-new-sale", label: "Nova Venda", href: "/pdv/sales", icon: AnimatedShoppingCartIcon, requiredPermissions: ["pdv.sales.read"] },
      { id: "pdv-history", label: "Histórico", href: "/pdv/history", icon: FileDescriptionIcon, requiredPermissions: ["pdv.access"] },
      { id: "pdv-closing", label: "Fechamento", href: "/pdv/closing", icon: FileDescriptionIcon, requiredPermissions: ["pdv.settings.write"] },
    ],
  },
  {
    id: "rpg",
    label: "RPG",
    href: "/rpg",
    icon: AnimatedDicesIcon,
    requiredPermissions: ["rpg.access"],
    children: [
      { id: "rpg-campaigns", label: "Campanhas", href: "/rpg/campaigns", icon: FileDescriptionIcon, requiredPermissions: ["rpg.campaigns.read"] },
      { id: "rpg-sessions", label: "Sessões", href: "/rpg/sessions", icon: FileDescriptionIcon, requiredPermissions: ["rpg.sessions.read"] },
      { id: "rpg-wiki", label: "Wiki", href: "/rpg/wiki", icon: FileDescriptionIcon, requiredPermissions: ["rpg.access"] },
    ],
  },
  {
    id: "wellness",
    label: "Bem-estar",
    href: "/wellness",
    icon: Heart,
    requiredPermissions: [],
    children: [
      { id: "wellness-today", label: "Hoje", href: "/wellness/today", icon: LayoutPanelTopIcon, requiredPermissions: [] },
      { id: "wellness-timeline", label: "Histórico", href: "/wellness/timeline", icon: FileDescriptionIcon, requiredPermissions: [] },
      { id: "wellness-stats", label: "Estatísticas", href: "/wellness/stats", icon: FileDescriptionIcon, requiredPermissions: [] },
      { id: "wellness-insights", label: "Insights", href: "/wellness/insights", icon: AnimatedLightbulbIcon, requiredPermissions: [] },
    ],
  },
  {
    id: "admin",
    label: "Administração",
    href: "/admin/users",
    icon: AnimatedGearIcon,
    requiredPermissions: ["admin.access"],
    children: [
      { id: "admin-organization", label: "Organização", href: "/admin/organization", icon: AnimatedGearIcon, requiredPermissions: [] },
      { id: "admin-access", label: "Acessos", href: "/admin/users", icon: UsersIcon, requiredPermissions: ["admin.users.manage", "admin.users.read", "admin.roles.read", "admin.roles.manage"] },
      { id: "admin-integrations", label: "Integrações", href: "/admin/integrations", icon: AnimatedGearIcon, requiredPermissions: [] },
      { id: "admin-platform", label: "Plataforma", href: "/saas/costing", icon: AnimatedGearIcon, requiredPermissions: ["admin.tenants.costs.read"] },
      { id: "admin-audit", label: "Auditoria", href: "/admin/audit", icon: FileDescriptionIcon, requiredPermissions: [] },
      { id: "admin-settings", label: "Configurações", href: "/admin/settings", icon: AnimatedGearIcon, requiredPermissions: ["admin.settings.write"] },
    ],
  },
];

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  "/dashboard": [],
  "/dashboard/tasks": [],
  "/dashboard/calendar": [],
  "/dashboard/notifications": [],
  "/pdv": ["pdv.access"],
  "/pdv/sales": ["pdv.sales.read"],
  "/pdv/products": ["pdv.products.manage"],
  "/pdv/inventory": ["pdv.inventory.read"],
  "/pdv/settings": ["pdv.settings.write"],
  "/pdv/history": ["pdv.access"],
  "/pdv/closing": ["pdv.settings.write"],
  "/crm/dashboard": ["crm.access"],
  "/crm/dashboard/overview": ["crm.access"],
  "/crm/dashboard/kpis": ["crm.access"],
  "/crm/dashboard/activity-feed": ["crm.access"],
  "/crm/dashboard/alerts": ["crm.access"],
  "/crm/sales": ["crm.access"],
  "/crm/sales/leads": ["crm.access"],
  "/crm/sales/opportunities": ["crm.access"],
  "/crm/sales/proposals": ["crm.access"],
  "/crm/sales/deals": ["crm.access"],
  "/crm/sales/quotes": ["crm.access"],
  "/crm/sales/contracts": ["crm.access"],
  "/crm/sales/orders": ["crm.access"],
  "/crm/customers": ["crm.access"],
  "/crm/customers/accounts": ["crm.access"],
  "/crm/customers/contacts": ["crm.access"],
  "/crm/customers/profiles": ["crm.access"],
  "/crm/customers/interaction-history": ["crm.access"],
  "/crm/customers/support-tickets": ["crm.access"],
  "/crm/inventory": ["crm.access"],
  "/crm/inventory/products": ["crm.access"],
  "/crm/inventory/categories": ["crm.access"],
  "/crm/inventory/stock-levels": ["crm.access"],
  "/crm/inventory/warehouses": ["crm.access"],
  "/crm/inventory/suppliers": ["crm.access"],
  "/crm/operations": ["crm.access"],
  "/crm/operations/order-fulfillment": ["crm.access"],
  "/crm/operations/shipping": ["crm.access"],
  "/crm/operations/returns": ["crm.access"],
  "/crm/operations/invoicing": ["crm.access"],
  "/crm/finance": ["crm.access"],
  "/crm/finance/invoices": ["crm.access"],
  "/crm/finance/payments": ["crm.access"],
  "/crm/finance/pricing-rules": ["crm.access"],
  "/crm/finance/taxes": ["crm.access"],
  "/crm/reports": ["crm.access"],
  "/crm/reports/analytics": ["crm.access"],
  "/crm/reports/sales-reports": ["crm.access"],
  "/crm/reports/customer-insights": ["crm.access"],
  "/crm/reports/inventory-reports": ["crm.access"],
  "/crm/reports/financial-reports": ["crm.access"],
  "/crm/reports/custom-reports": ["crm.access"],
  "/crm/automation": ["crm.access"],
  "/crm/automation/workflows": ["crm.access"],
  "/crm/automation/triggers": ["crm.access"],
  "/crm/automation/webhooks": ["crm.access"],
  "/crm/automation/integrations": ["crm.access"],
  "/crm/automation/ai-campaigns": ["crm.access"],
  "/crm/customers/ai-content": ["crm.access"],
  "/crm/ai-marketing": ["crm.access"],
  "/crm/ai-marketing/video": ["crm.access"],
  "/crm/ai-marketing/distribution": ["crm.access"],
  "/crm/administration": ["crm.access"],
  "/crm/administration/users": ["crm.access"],
  "/crm/administration/permissions": ["crm.access"],
  "/crm/administration/teams": ["crm.access"],
  "/crm/administration/audit-logs": ["crm.access"],
  "/crm/administration/system-settings": ["crm.access"],
  "/crm/settings": ["crm.access"],
  "/crm/settings/organization": ["crm.access"],
  "/crm/settings/custom-fields": ["crm.access"],
  "/crm/settings/pipelines": ["crm.access"],
  "/crm/settings/notifications": ["crm.access"],
  "/crm/settings/api-keys": ["crm.access"],
  "/crm": ["crm.access"],
  "/intelligence": [],
  "/intelligence/analytics": [],
  "/intelligence/forecasts": [],
  "/intelligence/insights": [],
  "/intelligence/automation": [],
  "/consumer": [],
  "/consumer/dashboard": [],
  "/erp/dashboard": ["erp.access"],
  "/erp/catalog": ["erp.access"],
  "/erp/catalog/:id": ["erp.access"],
  "/erp/purchasing": ["erp.access"],
  "/erp/suppliers": ["erp.access"],
  "/erp/logistics": ["erp.access"],
  "/erp/ai-content": ["erp.access"],
  "/finance/dashboard": ["finance.access"],
  "/ai/dashboard": ["ai.access"],
  "/erp": ["erp.access"],
  "/erp/inventory": ["erp.inventory.read"],
  "/erp/orders": ["erp.orders.read"],
  "/erp/settings": ["erp.settings.write"],
  "/finance": ["finance.access"],
  "/finance/transactions": ["finance.transactions.read"],
  "/finance/accounts": ["finance.accounts.manage"],
  "/finance/reports": ["finance.reports.view"],
  "/finance/investments": ["finance.investments.read"],
  "/finance/settings": ["finance.settings.write"],
  "/ai": ["ai.access"],
  "/ai/video": ["ai.access"],
  "/ai/images": ["ai.access"],
  "/ai/audio": ["ai.access"],
  "/ai/audio/tts": ["ai.access"],
  "/ai/audio/stt": ["ai.access"],
  "/ai/audio/music": ["ai.access"],
  "/ai/audio/voice": ["ai.access"],
  "/ai/audio/sfx": ["ai.access"],
  "/ai/audio/isolation": ["ai.access"],
  "/ai/audio/podcast": ["ai.access"],
  "/ai/books": ["ai.books.read"],
  "/ai/insights": ["ai.insights.view"],
  "/ai/avatar": ["ai.avatar.create"],
  "/ai/portrait": ["ai.portrait.create"],
  "/ai/retail": ["ai.access"],
  "/ai/retail/profile": ["ai.access"],
  "/ai/retail/content": ["ai.access"],
  "/ai/retail/video": ["ai.access"],
  "/ai/retail/distribution": ["ai.access"],
  "/ai/retail/attribution": ["ai.access"],
  "/ai/retail/billing": ["ai.access"],
  "/ai/retail/dashboard": ["ai.access"],
  "/ai/retail/studio": ["ai.access"],
  "/ai/studio": ["ai.access"],
  "/ai/social": ["ai.access"],
  "/rpg": ["rpg.access"],
  "/rpg/sessions": ["rpg.access"],
  "/rpg/sessions/:id": ["rpg.access"],
  "/rpg/campaigns": ["rpg.access"],
  "/rpg/campaigns/:id": ["rpg.access"],
  "/rpg/campaigns/new": ["rpg.access"],
  "/rpg/wiki": ["rpg.access"],
  "/rpg/rules": ["rpg.access"],
  "/rpg/characters": ["rpg.access"],
  "/omnichannel": ["omnichannel.access"],
  "/omnichannel/overview": ["omnichannel.access"],
  "/omnichannel/dashboard": ["omnichannel.access"],
  "/omnichannel/inbox": ["omnichannel.access"],
  "/omnichannel/inbox/conversations": ["omnichannel.access"],
  "/omnichannel/inbox/queues": ["omnichannel.access"],
  "/omnichannel/inbox/saved-views": ["omnichannel.access"],
  "/omnichannel/inbox/assigned": ["omnichannel.access"],
  "/omnichannel/inbox/unassigned": ["omnichannel.access"],
  "/omnichannel/sla-status": ["omnichannel.access"],
  "/omnichannel/customers": ["omnichannel.access"],
  "/omnichannel/agents": ["omnichannel.access"],
  "/omnichannel/automation": ["omnichannel.access"],
  "/omnichannel/automation/routing": ["omnichannel.access"],
  "/omnichannel/automation/sla": ["omnichannel.access"],
  "/omnichannel/automation/business-hours": ["omnichannel.access"],
  "/omnichannel/reports": ["omnichannel.access"],
  "/omnichannel/reports/conversations": ["omnichannel.access"],
  "/omnichannel/reports/agents": ["omnichannel.access"],
  "/omnichannel/reports/channels": ["omnichannel.access"],
  "/omnichannel/settings": ["omnichannel.access"],
  "/omnichannel/settings/organization": ["omnichannel.access"],
  "/omnichannel/settings/channels": ["omnichannel.access"],
  "/omnichannel/settings/access": ["omnichannel.access"],
  "/omnichannel/settings/integrations": ["omnichannel.access"],
  "/omnichannel/settings/system": ["omnichannel.access"],
  "/admin": ["admin.access"],
  "/admin/organization": ["admin.access"],
  "/admin/domains": ["admin.domains.read"],
  "/admin/domains/new": ["admin.domains.manage"],
  "/admin/domains/:id/edit": ["admin.domains.manage"],
  "/admin/domains/ssl": ["admin.domains.ssl_check"],
  "/admin/tenants": ["admin.tenants.manage"],
  "/admin/tenants/new": ["admin.tenants.manage"],
  "/admin/tenants/:id/edit": ["admin.tenants.manage"],
  "/admin/tenants/costs": ["admin.tenants.costs.read"],
  "/admin/tenants/:tenantId/costs": ["admin.tenants.costs.read"],
  "/admin/branches": ["admin.branches.manage"],
  "/admin/branches/new": ["admin.branches.manage"],
  "/admin/branches/:id/edit": ["admin.branches.manage"],
  "/admin/users": ["admin.users.manage", "admin.users.read"],
  "/admin/users/new": ["admin.users.manage"],
  "/admin/users/:id/edit": ["admin.users.manage"],
  "/admin/roles": ["admin.roles.read", "admin.roles.manage"],
  "/admin/menu": ["admin.menu.manage"],
  "/admin/settings": ["admin.settings.write"],
  "/admin/audit": ["admin.access"],
  "/admin/integrations": ["admin.access"],
  "/admin/costing": ["admin.tenants.costs.read"],
  "/admin/costs": ["admin.tenants.costs.read"],
  "/admin/usage": ["admin.usage.read"],
  "/admin/ai-models": ["admin.ai.models.manage"],
  "/admin/ai-requests": ["admin.usage.read"],
  "/dashboard/settings": ["admin.settings.read"],
  "/dashboard/profile": [],
  "/sso/users": ["admin.users.read"],
  "/saas/costing": ["admin.tenants.costs.read"],
  "/saas/tenants": ["admin.tenants.manage"],
  "/saas/usage": ["admin.usage.read"],
  "/saas/settings": ["admin.settings.write"],
  "/saas/branches": ["admin.branches.manage"],
  "/wellness": [],
  "/wellness/today": [],
  "/wellness/timeline": [],
  "/wellness/stats": [],
  "/wellness/insights": [],
};
